- name: Deploy xqueue-watcher
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    COMMON_APP_DIR: "/edx/app"
    common_web_group: "www-data"
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    ENABLE_NEWRELIC: False
  roles:
    - aws
    - datadog
    - splunkforwarder
    - newrelic
    - xqwatcher    
